# Generated by Django 5.1.7 on 2025-07-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='daily_exercise_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes of exercise per day'),
        ),
    ]
