# Generated by Django 5.2.1 on 2025-06-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_exerciseplan_price_exercisestep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('diet_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('VEGAN', 'Vegan'), ('PALEO', 'Paleo'), ('KETO', 'Ketogenic'), ('BAL', 'Balanced')], max_length=5)),
                ('calories_per_day', models.PositiveIntegerField(help_text='Target calories per day')),
                ('protein_grams', models.PositiveIntegerField(help_text='Target protein in grams')),
                ('carbs_grams', models.PositiveIntegerField(help_text='Target carbs in grams')),
                ('fat_grams', models.PositiveIntegerField(help_text='Target fat in grams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=29.99, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nutritionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meal_type', models.CharField(choices=[('BRK', 'Breakfast'), ('LUN', 'Lunch'), ('DIN', 'Dinner'), ('SNK', 'Snack')], max_length=3)),
                ('calories', models.PositiveIntegerField()),
                ('protein_grams', models.PositiveIntegerField()),
                ('carbs_grams', models.PositiveIntegerField()),
                ('fat_grams', models.PositiveIntegerField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('prep_time_minutes', models.PositiveIntegerField(default=15)),
                ('cooking_time_minutes', models.PositiveIntegerField(default=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutrition_meals/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='inventory.nutritionplan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.CreateModel(
            name='NutritionPlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('completed_meals', models.ManyToManyField(related_name='completed_by', to='inventory.nutritionmeal')),
                ('current_meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nutritionmeal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nutritionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
