# Generated by Django 5.1.7 on 2025-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_exerciseplan_daily_exercise_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionmeal',
            options={'ordering': ['day_of_week', 'meal_type', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='nutritionmeal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nutritionmeal',
            name='day_of_week',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Duration of the plan in days'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionmeal',
            unique_together={('plan', 'day_of_week', 'meal_type', 'order')},
        ),
    ]
